config/routes.rb
Rails.application.routes.draw do
  root 'vc_firms#home'
  resources :vc_firms, only: [:index, :show] do
    resources :startups, only: :index
  end
  resources :startups, only: [:show] do
    resources :founders, only: :index
  end
  resources :founders, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/founder.rb
class Founder < ApplicationRecord
  belongs_to :startup
  has_many :rounds, through: :startup
  has_many :vc_firms, through: :rounds
  mount_uploader :photo, PhotoUploader
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :vc_firm
  belongs_to :startup
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :vc_firm
end

app/models/startup.rb
class Startup < ApplicationRecord
  has_many :rounds
  has_many :vc_firms, through: :rounds
  has_many :founders
  mount_uploader :logo, PhotoUploader
end

app/models/vc_firm.rb
class VcFirm < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_name, :against => :name

  has_many :stages
  has_many :rounds
  has_many :startups, through: :rounds
  has_many :founders, through: :startups
  mount_uploader :logo, PhotoUploader

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/founders_controller.rb
class FoundersController < ApplicationController
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  def index
    @vc_firm = VcFirm.find(params[:vc_firm_id])
    @startups = @vc_firm.startups
  end

  def show
    @startup = Startup.find(params[:id])
  end
end

app/controllers/vc_firms_controller.rb
class VcFirmsController < ApplicationController
  def home
      @vc_firms = VcFirm.all
  end

  def index
    if params[:query].nil?
      @vc_firms = VcFirm.all
    elsif params[:query] == "seed_stage"
      @vc_firms = VcFirm.where.not(:seed_stage => nil)
    elsif params[:query] == "series_a"
      @vc_firms = VcFirm.where.not(:series_a => nil)
    elsif params[:query] == "series_b"
      @vc_firms = VcFirm.where.not(:series_b => nil)
    elsif params[:query] == "series_c"
      @vc_firms = VcFirm.where.not(:series_c => nil)
    elsif params[:query] == "growth_stage"
      @vc_firms = VcFirm.where.not(:growth_stage => nil)
    end
  end

  def show
    @vc_firm = VcFirm.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/founders_helper.rb
module FoundersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/vc_firms_helper.rb
module VcFirmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vcdirectory</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src=<%= image_path('logo.png')%> />
  </a>
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   <ul class="nav navbar-nav">

  <li><a href="/vc_firms">All VCs</a></li>
  <li><a href="/vc_firms?query=seed_stage">Seed Stage</a></li>
  <li><a href="/vc_firms?query=series_a">Series A</a></li>
  <li><a href="/vc_firms?query=series_b">Series B</a></li>
  <li><a href="/vc_firms?query=series_c">Series C</a></li>
  <li><a href="/vc_firms?query=growth_stage">Growth Stage</a></li>
  </ul>
  </div>

    <!-- Search form -->
    <form action="/vc_firms/index" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Look for a VC">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
  </div>
    <%= yield %>
  </body>
</html>

app/views/startups/index.html.erb
<div class="text-center">
<h1><%= @vc_firm.name%></h1>
<h2>Investments</h2>
<ul class="list-unstyled">
  <% @startups.each do |startup| %>
  <li>
    <%= link_to startup.name, startup_path(startup)  %>
  </li>
  <% end %>
</ul>
</div>

app/views/startups/show.html.erb
<div class="text-center">
  <h1><%= @startup.name %></h1>
  <p><%= @startup.description %></p>
  <div class="container">
    <div class="row">
    <div class="col-xs-4">
      <div class="show-box">
        <h2>Description</h2>
      </div>
    </div>
      <div class="col-xs-4">
        <div class="show-box">
          <h2>Founders</h2>
          <% @startup.founders.each do |founder| %>
          <h2>founder.name</h2>
          <p>founder.email</p>
          <p>founder.phone</p>
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="show-box">
          <h2>VC firms they raised with</h2>
            <% @startup.vc_firms.each do  |vc| %>
            <p> <%= link_to vc.name, vc_firm_path(vc) %> </p>
            <% end %>
        </div>

      </div>
      </div>
    </div>
  </div>
</div>

app/views/vc_firms/home.html.erb
<div class="banner" style="background: linear-gradient(to top right, #114357 , #F29492);">
  <div class="banner-content">
    <h1>ICEBERG</h1>
    <p>Brisez la glace. Découvrez les meilleurs VCs de France.</p>
    <a href="/vc_firms" class="btn btn-treehouse">Découvrir la liste</a>
  </div>
</div>

app/views/vc_firms/index.html.erb
<!--
<div class="wrapper" style="padding: 20px">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-md-2 col-md-offset-1">
        <%#= link_to "Seed stage", '/vc_firms?query=seed_stage', class: "btn btn-treehouse" %>
      </div>
      <div class="col-xs-6 col-md-2">
        <%#= link_to "Series A", '/vc_firms?query=series_a', class: "btn btn-treehouse" %>
      </div>
      <div class="col-xs-6 col-md-2">
        <%#= link_to "Series B", '/vc_firms?query=series_b', class: "btn btn-treehouse" %>

      </div>
      <div class="col-xs-6 col-md-2">
        <%#= link_to "Series C", '/vc_firms?query=series_c', class: "btn btn-treehouse" %>

      </div>
      <div class="col-xs-6 col-md-2">
        <%#= link_to "Growth stage", '/vc_firms?query=growth_stage', class: "btn btn-treehouse" %>

      </div>
    </div>
  </div>
</div> -->

<div class="wrapper">
<div class="container">
  <div class="row">
    <% @vc_firms.each do |vc_firm| %>
    <div class="col-xs-12 col-sm-4 col-md-3">
      <div class="card" style="background-color: #114357">
        <div class="card-category"><%= vc_firm.category %></div>
        <div class="card-description">
          <h2><%= vc_firm.name %></h2>
          <p><%if vc_firm.seed_stage%>Seed stage <% end %><%if vc_firm.series_a%>Series A <% end %> <%if vc_firm.series_b%>Series B <% end %><%if vc_firm.series_c%>Series C <% end %><%if vc_firm.growth_stage%>Growth stage<% end %></p>
        </div>
        <%= cl_image_tag vc_firm.logo, class: "card-user avatar-large"%>
        <%= link_to "", vc_firm_path(vc_firm), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/vc_firms/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>  <a target="_blank" href= <%=  @vc_firm.website %>><%= cl_image_tag(@vc_firm.logo,
      width: 100, height: 70, crop: :fill) %></a>

    </h1>
    <div class="row">
      <div class="col-xs-4">
        <div class="text-center show-box">
          <h2>Infos</h2>
          <% if @vc_firm.description %>
          <p>Description: <%= @vc_firm.description %></p>
          <% end %>
          <% if @vc_firm.office_address %>
          <p>Address: <%= @vc_firm.office_address %></p>
          <% end %>
          <% if @vc_firm.vc_type %>
          <p>Type : <%= @vc_firm.vc_type %></p>
          <% end %>
          <% if @vc_firm.sector %>
          <p>Secteurs : <%= @vc_firm.sector %></p>
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="text-center show-box">
          <h2>Portfolio companies</h2>
          <% @vc_firm.startups.each do |startup| %>
          <p><%= link_to startup.name, startup_path(startup)  %></p>
          <% end %>
          <p><%= link_to "All investments", vc_firm_startups_path(@vc_firm) %></p>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="text-center show-box">
        <h2>Get in touch</h2>
          <% if @vc_firm.website %>
          <%= link_to "", @vc_firm.website, class: "fa fa-link", target: '_blank', style: "text-decoration: none ; font-size: 30px; margin: 15px"  %>
          <% end %>
          <% if @vc_firm.facebook %>
          <%= link_to "", @vc_firm.facebook, class: "fa fa-facebook", target: '_blank', style: "text-decoration: none ; font-size: 30px; margin: 15px"  %>
          <% end %>
          <% if @vc_firm.twitter %>
          <%= link_to "", @vc_firm.twitter, class: "fa fa-twitter", target: '_blank', style: "text-decoration: none; font-size: 30px; margin: 15px"  %>
          <% end %>
          <% if @vc_firm.office_address %>
          <p>Adresse: <%= @vc_firm.office_address %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>